apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: avradio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:

  rules:
  - host: avradio-beta.harmony.newearthart.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress 
          servicePort: 80                    

---  

apiVersion: v1
kind: Service
metadata:
    name: sql
    labels:
        app: mysql
spec:
    clusterIP: None
    selector:
        app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-node
spec:
  serviceName: mysql
  selector:
    matchLabels:
        app: mysql
  replicas: 1
  template:
    metadata:
        labels:
            app: mysql
    spec:
        containers:
        -   name: mysql
            image: mysql:5.7
    
            env:
            -   name: MYSQL_ROOT_PASSWORD
                value: "wordpress"

            -   name: MYSQL_DATABASE
                value: "wordpress"

            -   name: MYSQL_USER
                value: "wordpress"

            -   name: MYSQL_PASSWORD
                value: "wordpress"

---
apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
#    clusterIP: None
    selector:
        app: wordpress

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: wordpress
spec:
  serviceName: wordpress
  selector:
    matchLabels:
        app: wordpress
  replicas: 1
  template:
    metadata:
        labels:
            app: wordpress
    spec:
        imagePullSecrets:
        - name: secret-cloudconnect
        containers:
        -   name: wordpress
            image: cloudconnect.scanrev.com:5000/av_radio_wp:1.1
            volumeMounts:
            -   mountPath: "/var/www/html/wp-content/themes/rev"
                name: site-data
            ports:
            -   containerPort: 80
            env:
            -   name: WORDPRESS_DB_HOST
                value: "sql:3306"

            -   name: WORDPRESS_DB_USER
                value: "wordpress"

            -   name: WORDPRESS_DB_PASSWORD
                value: "wordpress"

            -   name: XDEBUG_CONFIG
                value: "remote_host=host.docker.internal"

  volumeClaimTemplates:
  - metadata:
        name: site-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi



          


    


          

